language: node_js
node_js:
  - "10.13.0"
jobs:
  include:
    - stage: tests
      script:
        - cd web
        - yarn install
        - yarn test
    - # stage name not required, will continue to use `test`
      script:
        - cd server
        - yarn install
        - yarn test
    - stage: build
      script:
        - cd web
        - yarn build
    - # stage name not required, will continue to use `build`
      script:
        - cd server
        - yarn build